import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Midu Libritos",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <main className="px-4 m-auto grid min-h-screen max-w-screen-lg grid-rows-[60px,1fr,60px] gap-4 ">
          <nav className="felx items-center text-2xl">nav</nav>
          <section>{children}</section>
          <footer className="felx items-center justify-center">****</footer>
        </main>
        </body>
    </html>
  );
}
